apiVersion: apps/v1
kind: Deployment
metadata:
  name: juanes-deployment
  labels:
    app: juanes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: juanes
  template:
    metadata:
      labels:
        app: juanes
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
